version: '3' # specify docker-compose version
 
# Define the services/containers to be run
services:
 client:
   build: ./client
   ports:
      - "4200:4200"
 server: # name of the first service
   build: ./server # specify the directory of the Dockerfile
   ports:
      - "8080:8080"
   env_file:
      - .env
   environment:
      - MONGO_URL=mongodb://database/app
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}  
   links:
     - database
   depends_on:
       - database
 database: # name of the third service
   image: mongo # specify image to build container from
   env_file:
      - .env
   environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=app
   ports:
     - "27017:27017" # specify port forewarding